[env:thinknode-m2-raamses]
custom_meshtastic_hw_model = 0
custom_meshtastic_hw_model_slug = THINKNODE_M2_RAAMSES
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = ThinkNode M2 (Raamses)
custom_meshtastic_tags = Elecrow, ThinkNode, Raamses
custom_meshtastic_partition_scheme = 4MB
 
extends = esp32s3_base
board = ESP32-S3-WROOM-1-N4
board_level = extra
build_flags = 
  ${esp32s3_base.build_flags}
  -D THINKNODE_M2
  -D THINKNODE_M2_RAAMSES
  -D HAS_RAAMSES
  -D BOARD_HAS_PSRAM
  -D HAS_SCREEN
  -D RAAMSES_GATEWAY_HOST=\"192.168.6.230\"
  -D RAAMSES_GATEWAY_PORT=8765
  -D RAAMSES_DEVICE_TYPE=\"thinknode_m2\"
  -D RAAMSES_WIFI_SSID=\"seanrohde\"
  -D RAAMSES_WIFI_PASS=\"piperbbs123\"
  -D VIBRATION_MOTOR_PIN=-1
  -I variants/esp32s3/thinknode_m2_raamses
