[env:heltec-v4-raamses]
custom_meshtastic_hw_model = 43
custom_meshtastic_hw_model_slug = HELTEC_V4_RAAMSES
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Heltec V4 (Raamses)
custom_meshtastic_images = heltec-v3.svg, heltec-v3-case.svg
custom_meshtastic_tags = Heltec, Raamses
custom_meshtastic_partition_scheme = 16MB
 
extends = esp32s3_base
board = heltec_v4
board_level = pr
board_check = true
board_build.partitions = default_16MB.csv
build_flags = 
  ${esp32s3_base.build_flags}
  -D HELTEC_V4
  -D HELTEC_V4_RAAMSES
  -D HAS_RAAMSES
  -D HAS_SCREEN
  -D RAAMSES_GATEWAY_HOST=\"192.168.6.230\"
  -D RAAMSES_GATEWAY_PORT=8765
  -D RAAMSES_DEVICE_TYPE=\"heltec_v4\"
  -D RAAMSES_WIFI_SSID=\"seanrohde\"
  -D RAAMSES_WIFI_PASS=\"piperbbs123\"
  -D VIBRATION_MOTOR_PIN=21
  -I variants/esp32s3/heltec_v4_raamses
